spring.application.name=Douglas
server.port=${PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.jpa.database-platform=${DB_PLATFORM}
spring.jackson.mapper.SORT_PROPERTIES_ALPHABETICALLY=false

#Carpeta donde se guardaran los archivos(img) subidos
file.upload-dir = ./uploads

#Límites de tamaño para las subidas
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB